CREATE TABLE A_DFD_A06CFM56_LIST  (
   ID                   NUMBER(18)                      NOT NULL,
   MSG_NO               NUMBER(18),
   ACNUM                VARCHAR2(16),
   RPTDATE              DATE,
   CODE                 VARCHAR2(16),
   ESN_1                VARCHAR2(16),
   EHRS_1               NUMBER(24),
   ERT_1                NUMBER(24),
   ECYC_1               NUMBER(24),
   AP_1                 VARCHAR2(16),
   TR_1                 NUMBER(10),
   TR_2                 NUMBER(10),
   ESN_2                VARCHAR2(16),
   EHRS_2               NUMBER(24),
   ERT_2                NUMBER(24),
   ECYC_2               NUMBER(24),
   AP_2                 VARCHAR2(16),
   N1_S1                NUMBER(8,3),
   N1C_S1               NUMBER(8,3),
   N2_S1                NUMBER(8,3),
   EGT_S1               NUMBER(8,3),
   FF_S1                NUMBER(8,3),
   P3_S1                NUMBER(8,3),
   T3_S1                NUMBER(8,3),
   N1_S2                NUMBER(8,3),
   N1C_S2               NUMBER(8,3),
   N2_S2                NUMBER(8,3),
   EGT_S2               NUMBER(8,3),
   FF_S2                NUMBER(8,3),
   P3_S2                NUMBER(8,3),
   T3_S2                NUMBER(8,3),
   N1_S3                NUMBER(8,3),
   N1C_S3               NUMBER(8,3),
   N2_S3                NUMBER(8,3),
   EGT_S3               NUMBER(8,3),
   FF_S3                NUMBER(8,3),
   P3_S3                NUMBER(8,3),
   T3_S3                NUMBER(8,3),
   N1_S4                NUMBER(8,3),
   N1C_S4               NUMBER(8,3),
   N2_S4                NUMBER(8,3),
   EGT_S4               NUMBER(8,3),
   FF_S4                NUMBER(8,3),
   P3_S4                NUMBER(8,3),
   T3_S4                NUMBER(8,3),
   N1_S5                NUMBER(8,3),
   N1C_S5               NUMBER(8,3),
   N2_S5                NUMBER(8,3),
   EGT_S5               NUMBER(8,3),
   FF_S5                NUMBER(8,3),
   P3_S5                NUMBER(8,3),
   T3_S5                NUMBER(8,3),
   N1_S6                NUMBER(8,3),
   N1C_S6               NUMBER(8,3),
   N2_S6                NUMBER(8,3),
   EGT_S6               NUMBER(8,3),
   FF_S6                NUMBER(8,3),
   P3_S6                NUMBER(8,3),
   T3_S6                NUMBER(8,3),
   N1_S7                NUMBER(8,3),
   N1C_S7               NUMBER(8,3),
   N2_S7                NUMBER(8,3),
   EGT_S7               NUMBER(8,3),
   FF_S7                NUMBER(8,3),
   P3_S7                NUMBER(8,3),
   T3_S7                NUMBER(8,3),
   N1_S8                NUMBER(8,3),
   N1C_S8               NUMBER(8,3),
   N2_S8                NUMBER(8,3),
   EGT_S8               NUMBER(8,3),
   FF_S8                NUMBER(8,3),
   P3_S8                NUMBER(8,3),
   T3_S8                NUMBER(8,3),
   N1_S9                NUMBER(8,3),
   N1C_S9               NUMBER(8,3),
   N2_S9                NUMBER(8,3),
   EGT_S9               NUMBER(8,3),
   FF_S9                NUMBER(8,3),
   P3_S9                NUMBER(8,3),
   T3_S9                NUMBER(8,3),
   T5_V1                NUMBER(8,3),
   P25_V1               NUMBER(8,3),
   T25_V1               NUMBER(8,3),
   PT2_V1               NUMBER(8,3),
   ECW1_V1              NUMBER(8,3),
   VBV_V1               NUMBER(8,3),
   VSV_V1               NUMBER(8,3),
   T5_V2                NUMBER(8,3),
   P25_V2               NUMBER(8,3),
   T25_V2               NUMBER(8,3),
   PT2_V2               NUMBER(8,3),
   ECW1_V2              NUMBER(8,3),
   VBV_V2               NUMBER(8,3),
   VSV_V2               NUMBER(8,3),
   T5_V3                NUMBER(8,3),
   P25_V3               NUMBER(8,3),
   T25_V3               NUMBER(8,3),
   PT2_V3               NUMBER(8,3),
   ECW1_V3              NUMBER(8,3),
   VBV_V3               NUMBER(8,3),
   VSV_V3               NUMBER(8,3),
   T5_V4                NUMBER(8,3),
   P25_V4               NUMBER(8,3),
   T25_V4               NUMBER(8,3),
   PT2_V4               NUMBER(8,3),
   ECW1_V4              NUMBER(8,3),
   VBV_V4               NUMBER(8,3),
   VSV_V4               NUMBER(8,3),
   T5_V5                NUMBER(8,3),
   P25_V5               NUMBER(8,3),
   T25_V5               NUMBER(8,3),
   PT2_V5               NUMBER(8,3),
   ECW1_V5              NUMBER(8,3),
   VBV_V5               NUMBER(8,3),
   VSV_V5               NUMBER(8,3),
   T5_V6                NUMBER(8,3),
   P25_V6               NUMBER(8,3),
   T25_V6               NUMBER(8,3),
   PT2_V6               NUMBER(8,3),
   ECW1_V6              NUMBER(8,3),
   VBV_V6               NUMBER(8,3),
   VSV_V6               NUMBER(8,3),
   T5_V7                NUMBER(8,3),
   P25_V7               NUMBER(8,3),
   T25_V7               NUMBER(8,3),
   PT2_V7               NUMBER(8,3),
   ECW1_V7              NUMBER(8,3),
   VBV_V7               NUMBER(8,3),
   VSV_V7               NUMBER(8,3),
   T5_V8                NUMBER(8,3),
   P25_V8               NUMBER(8,3),
   T25_V8               NUMBER(8,3),
   PT2_V8               NUMBER(8,3),
   ECW1_V8              NUMBER(8,3),
   VBV_V8               NUMBER(8,3),
   VSV_V8               NUMBER(8,3),
   T5_V9                NUMBER(8,3),
   P25_V9               NUMBER(8,3),
   T25_V9               NUMBER(8,3),
   PT2_V9               NUMBER(8,3),
   ECW1_V9              NUMBER(8,3),
   VBV_V9               NUMBER(8,3),
   VSV_V9               NUMBER(8,3),
   T5_X1                NUMBER(8,3),
   P25_X1               NUMBER(8,3),
   T25_X1               NUMBER(8,3),
   ECW1_X1              NUMBER(8,3),
   PT2_X1               NUMBER(8,3),
   VBV_X1               NUMBER(8,3),
   VSV_X1               NUMBER(8,3),
   T5_X2                NUMBER(8,3),
   P25_X2               NUMBER(8,3),
   T25_X2               NUMBER(8,3),
   ECW1_X2              NUMBER(8,3),
   PT2_X2               NUMBER(8,3),
   VBV_X2               NUMBER(8,3),
   VSV_X2               NUMBER(8,3),
   T5_X3                NUMBER(8,3),
   P25_X3               NUMBER(8,3),
   T25_X3               NUMBER(8,3),
   ECW1_X3              NUMBER(8,3),
   PT2_X3               NUMBER(8,3),
   VBV_X3               NUMBER(8,3),
   VSV_X3               NUMBER(8,3),
   T5_X4                NUMBER(8,3),
   P25_X4               NUMBER(8,3),
   T25_X4               NUMBER(8,3),
   ECW1_X4              NUMBER(8,3),
   PT2_X4               NUMBER(8,3),
   VBV_X4               NUMBER(8,3),
   VSV_X4               NUMBER(8,3),
   T5_X5                NUMBER(8,3),
   P25_X5               NUMBER(8,3),
   T25_X5               NUMBER(8,3),
   ECW1_X5              NUMBER(8,3),
   PT2_X5               NUMBER(8,3),
   VBV_X5               NUMBER(8,3),
   VSV_X5               NUMBER(8,3),
   T5_X6                NUMBER(8,3),
   P25_X6               NUMBER(8,3),
   T25_X6               NUMBER(8,3),
   ECW1_X6              NUMBER(8,3),
   PT2_X6               NUMBER(8,3),
   VBV_X6               NUMBER(8,3),
   VSV_X6               NUMBER(8,3),
   T5_X7                NUMBER(8,3),
   P25_X7               NUMBER(8,3),
   T25_X7               NUMBER(8,3),
   ECW1_X7              NUMBER(8,3),
   PT2_X7               NUMBER(8,3),
   VBV_X7               NUMBER(8,3),
   VSV_X7               NUMBER(8,3),
   T5_X8                NUMBER(8,3),
   P25_X8               NUMBER(8,3),
   T25_X8               NUMBER(8,3),
   ECW1_X8              NUMBER(8,3),
   PT2_X8               NUMBER(8,3),
   VBV_X8               NUMBER(8,3),
   VSV_X8               NUMBER(8,3),
   T5_X9                NUMBER(8,3),
   P25_X9               NUMBER(8,3),
   T25_X9               NUMBER(8,3),
   ECW1_X9              NUMBER(8,3),
   PT2_X9               NUMBER(8,3),
   VBV_X9               NUMBER(8,3),
   VSV_X9               NUMBER(8,3),
   N1_T1                NUMBER(8,3),
   N1C_T1               NUMBER(8,3),
   EGT_T1               NUMBER(8,3),
   FF_T1                NUMBER(8,3),
   P3_T1                NUMBER(8,3),
   T3_T1                NUMBER(8,3),
   N2_T1                NUMBER(8,3),
   N1_T2                NUMBER(8,3),
   N1C_T2               NUMBER(8,3),
   EGT_T2               NUMBER(8,3),
   FF_T2                NUMBER(8,3),
   P3_T2                NUMBER(8,3),
   T3_T2                NUMBER(8,3),
   N2_T2                NUMBER(8,3),
   N1_T3                NUMBER(8,3),
   N1C_T3               NUMBER(8,3),
   EGT_T3               NUMBER(8,3),
   FF_T3                NUMBER(8,3),
   P3_T3                NUMBER(8,3),
   T3_T3                NUMBER(8,3),
   N2_T3                NUMBER(8,3),
   N1_T4                NUMBER(8,3),
   N1C_T4               NUMBER(8,3),
   EGT_T4               NUMBER(8,3),
   FF_T4                NUMBER(8,3),
   P3_T4                NUMBER(8,3),
   T3_T4                NUMBER(8,3),
   N2_T4                NUMBER(8,3),
   N1_T5                NUMBER(8,3),
   N1C_T5               NUMBER(8,3),
   EGT_T5               NUMBER(8,3),
   FF_T5                NUMBER(8,3),
   P3_T5                NUMBER(8,3),
   T3_T5                NUMBER(8,3),
   N2_T5                NUMBER(8,3),
   N1_T6                NUMBER(8,3),
   N1C_T6               NUMBER(8,3),
   EGT_T6               NUMBER(8,3),
   FF_T6                NUMBER(8,3),
   P3_T6                NUMBER(8,3),
   T3_T6                NUMBER(8,3),
   N2_T6                NUMBER(8,3),
   N1_T7                NUMBER(8,3),
   N1C_T7               NUMBER(8,3),
   EGT_T7               NUMBER(8,3),
   FF_T7                NUMBER(8,3),
   P3_T7                NUMBER(8,3),
   T3_T7                NUMBER(8,3),
   N2_T7                NUMBER(8,3),
   N1_T8                NUMBER(8,3),
   N1C_T8               NUMBER(8,3),
   EGT_T8               NUMBER(8,3),
   FF_T8                NUMBER(8,3),
   P3_T8                NUMBER(8,3),
   T3_T8                NUMBER(8,3),
   N2_T8                NUMBER(8,3),
   N1_T9                NUMBER(8,3),
   N1C_T9               NUMBER(8,3),
   EGT_T9               NUMBER(8,3),
   FF_T9                NUMBER(8,3),
   P3_T9                NUMBER(8,3),
   T3_T9                NUMBER(8,3),
   N2_T9                NUMBER(8,3),
   UPDATE_DATE          DATE,
   E                    NUMBER(8,3),
   MAX                  NUMBER(8,3),
   LIM                  NUMBER(8,3),
   REF                  NUMBER(8,3),
   TOL                  NUMBER(8,3),
   TTP                  NUMBER(8,3),
   Y1                   NUMBER(8,3),
   Y2                   NUMBER(8,3),
   PSEL                  VARCHAR2(24)
);

COMMENT ON COLUMN A_DFD_A06CFM56_LIST.ID IS
'系统编号';

COMMENT ON COLUMN A_DFD_A06CFM56_LIST.MSG_NO IS
'报文编号';

COMMENT ON COLUMN A_DFD_A06CFM56_LIST.ACNUM IS
'飞机号';

COMMENT ON COLUMN A_DFD_A06CFM56_LIST.RPTDATE IS
'报文时间
2012-1-1 00:00:00';

COMMENT ON COLUMN A_DFD_A06CFM56_LIST.CODE IS
'发送编码';

/*==============================================================*/
/* Index: "INDEX_221"                                           */
/*==============================================================*/
CREATE INDEX "INDEX_221" ON A_DFD_A06CFM56_LIST (
   MSG_NO ASC
);

/*==============================================================*/
/* Index: "INDEX_222"                                           */
/*==============================================================*/
CREATE INDEX "INDEX_222" ON A_DFD_A06CFM56_LIST (
   ACNUM ASC
);

/*==============================================================*/
/* Index: "INDEX_223"                                           */
/*==============================================================*/
CREATE INDEX "INDEX_223" ON A_DFD_A06CFM56_LIST (
   RPTDATE ASC
);
