CREATE TABLE "A_DFD_A06IAEV25_LIST"  (
   ID                   NUMBER(18)                      NOT NULL,
   MSG_NO               NUMBER(18),
   ACNUM                VARCHAR2(16),
   RPTDATE              DATE,
   CODE                 VARCHAR2(16),
   ESN_1                VARCHAR2(16),
   EHRS_1               NUMBER(8,3),
   ECYC_1               NUMBER(8,3),
   AP_1                 VARCHAR2(16),
   HPT_1                 NUMBER(8,3),
   SVA_1                 NUMBER(8,3),
   BAF_1                VARCHAR2(16),
   LP_1                 NUMBER(8,3),
   ESN_2                VARCHAR2(16),
   EHRS_2               NUMBER(8,3),
   ECYC_2               NUMBER(8,3),
   AP_2                 VARCHAR2(16),
   HPT_2                 NUMBER(8,3),
   SVA_2                 NUMBER(8,3),
   BAF_2                VARCHAR2(16),
   LP_2                 NUMBER(8,3),
   E                    NUMBER(8,3),
   MAX                  NUMBER(8,3),
   LIM                  NUMBER(8,3),
   REF                  NUMBER(8,3),
   TOL                  NUMBER(8,3),
   TTP                  NUMBER(8,3),
   Y1                   NUMBER(8,3),
   Y2                   NUMBER(8,3),
   PARA                 NUMBER(8,3),
   EPR_S1               NUMBER(8,3),
   EGT_S1               NUMBER(8,3),
   N1_S1                NUMBER(8,3),
   N2_S1                NUMBER(8,3),
   FF_S1                NUMBER(8,3),
   P3_S1                NUMBER(8,3),
   T3_S1                NUMBER(8,3),
   EPR_S2               NUMBER(8,3),
   EGT_S2               NUMBER(8,3),
   N1_S2                NUMBER(8,3),
   N2_S2                NUMBER(8,3),
   FF_S2                NUMBER(8,3),
   P3_S2                NUMBER(8,3),
   T3_S2                NUMBER(8,3),
   EPR_S3               NUMBER(8,3),
   EGT_S3               NUMBER(8,3),
   N1_S3                NUMBER(8,3),
   N2_S3                NUMBER(8,3),
   FF_S3                NUMBER(8,3),
   P3_S3                NUMBER(8,3),
   T3_S3                NUMBER(8,3),
   EPR_S4               NUMBER(8,3),
   EGT_S4               NUMBER(8,3),
   N1_S4                NUMBER(8,3),
   N2_S4                NUMBER(8,3),
   FF_S4                NUMBER(8,3),
   P3_S4                NUMBER(8,3),
   T3_S4                NUMBER(8,3),
   EPR_S5               NUMBER(8,3),
   EGT_S5               NUMBER(8,3),
   N1_S5                NUMBER(8,3),
   N2_S5                NUMBER(8,3),
   FF_S5                NUMBER(8,3),
   P3_S5                NUMBER(8,3),
   T3_S5                NUMBER(8,3),
   EPR_S6               NUMBER(8,3),
   EGT_S6               NUMBER(8,3),
   N1_S6                NUMBER(8,3),
   N2_S6                NUMBER(8,3),
   FF_S6                NUMBER(8,3),
   P3_S6                NUMBER(8,3),
   T3_S6                NUMBER(8,3),
   EPR_S7               NUMBER(8,3),
   EGT_S7               NUMBER(8,3),
   N1_S7                NUMBER(8,3),
   N2_S7                NUMBER(8,3),
   FF_S7                NUMBER(8,3),
   P3_S7                NUMBER(8,3),
   T3_S7                NUMBER(8,3),
   EPR_S8               NUMBER(8,3),
   EGT_S8               NUMBER(8,3),
   N1_S8                NUMBER(8,3),
   N2_S8                NUMBER(8,3),
   FF_S8                NUMBER(8,3),
   P3_S8                NUMBER(8,3),
   T3_S8                NUMBER(8,3),
   EPR_S9               NUMBER(8,3),
   EGT_S9               NUMBER(8,3),
   N1_S9                NUMBER(8,3),
   N2_S9                NUMBER(8,3),
   FF_S9                NUMBER(8,3),
   P3_S9                NUMBER(8,3),
   T3_S9                NUMBER(8,3),
   EPR_T1               NUMBER(8,3),
   EGT_T1               NUMBER(8,3),
   N1_T1                NUMBER(8,3),
   N2_T1                NUMBER(8,3),
   FF_T1                NUMBER(8,3),
   P3_T1                NUMBER(8,3),
   T3_T1                NUMBER(8,3),
   EPR_T2               NUMBER(8,3),
   EGT_T2               NUMBER(8,3),
   N1_T2                NUMBER(8,3),
   N2_T2                NUMBER(8,3),
   FF_T2                NUMBER(8,3),
   P3_T2                NUMBER(8,3),
   T3_T2                NUMBER(8,3),
   EPR_T3               NUMBER(8,3),
   EGT_T3               NUMBER(8,3),
   N1_T3                NUMBER(8,3),
   N2_T3                NUMBER(8,3),
   FF_T3                NUMBER(8,3),
   P3_T3                NUMBER(8,3),
   T3_T3                NUMBER(8,3),
   EPR_T4               NUMBER(8,3),
   EGT_T4               NUMBER(8,3),
   N1_T4                NUMBER(8,3),
   N2_T4                NUMBER(8,3),
   FF_T4                NUMBER(8,3),
   P3_T4                NUMBER(8,3),
   T3_T4                NUMBER(8,3),
   EPR_T5               NUMBER(8,3),
   EGT_T5               NUMBER(8,3),
   N1_T5                NUMBER(8,3),
   N2_T5                NUMBER(8,3),
   FF_T5                NUMBER(8,3),
   P3_T5                NUMBER(8,3),
   T3_T5                NUMBER(8,3),
   EPR_T6               NUMBER(8,3),
   EGT_T6               NUMBER(8,3),
   N1_T6                NUMBER(8,3),
   N2_T6                NUMBER(8,3),
   FF_T6                NUMBER(8,3),
   P3_T6                NUMBER(8,3),
   T3_T6                NUMBER(8,3),
   EPR_T7               NUMBER(8,3),
   EGT_T7               NUMBER(8,3),
   N1_T7                NUMBER(8,3),
   N2_T7                NUMBER(8,3),
   FF_T7                NUMBER(8,3),
   P3_T7                NUMBER(8,3),
   T3_T7                NUMBER(8,3),
   EPR_T8               NUMBER(8,3),
   EGT_T8               NUMBER(8,3),
   N1_T8                NUMBER(8,3),
   N2_T8                NUMBER(8,3),
   FF_T8                NUMBER(8,3),
   P3_T8                NUMBER(8,3),
   T3_T8                NUMBER(8,3),
   EPR_T9               NUMBER(8,3),
   EGT_T9               NUMBER(8,3),
   N1_T9                NUMBER(8,3),
   N2_T9                NUMBER(8,3),
   FF_T9                NUMBER(8,3),
   P3_T9                NUMBER(8,3),
   T3_T9                NUMBER(8,3),
   EPRC_V1              NUMBER(8,3),
   T2_V1                NUMBER(8,3),
   P2_V1                NUMBER(8,3),
   MN_V1                NUMBER(8,3),
   ECW3_V1              NUMBER(8,3),
   ECW4_V1              NUMBER(8,3),
   TRP_V1               NUMBER(8,3),
   EPRC_V2              NUMBER(8,3),
   T2_V2                NUMBER(8,3),
   P2_V2                NUMBER(8,3),
   MN_V2                NUMBER(8,3),
   ECW3_V2              NUMBER(8,3),
   ECW4_V2              NUMBER(8,3),
   TRP_V2               NUMBER(8,3),
   EPRC_V3              NUMBER(8,3),
   T2_V3                NUMBER(8,3),
   P2_V3                NUMBER(8,3),
   MN_V3                NUMBER(8,3),
   ECW3_V3              NUMBER(8,3),
   ECW4_V3              NUMBER(8,3),
   TRP_V3               NUMBER(8,3),
   EPRC_V4              NUMBER(8,3),
   T2_V4                NUMBER(8,3),
   P2_V4                NUMBER(8,3),
   MN_V4                NUMBER(8,3),
   ECW3_V4              NUMBER(8,3),
   ECW4_V4              NUMBER(8,3),
   TRP_V4               NUMBER(8,3),
   EPRC_V5              NUMBER(8,3),
   T2_V5                NUMBER(8,3),
   P2_V5                NUMBER(8,3),
   MN_V5                NUMBER(8,3),
   ECW3_V5              NUMBER(8,3),
   ECW4_V5              NUMBER(8,3),
   TRP_V5               NUMBER(8,3),
   EPRC_V6              NUMBER(8,3),
   T2_V6                NUMBER(8,3),
   P2_V6                NUMBER(8,3),
   MN_V6                NUMBER(8,3),
   ECW3_V6              NUMBER(8,3),
   ECW4_V6              NUMBER(8,3),
   TRP_V6               NUMBER(8,3),
   EPRC_V7              NUMBER(8,3),
   T2_V7                NUMBER(8,3),
   P2_V7                NUMBER(8,3),
   MN_V7                NUMBER(8,3),
   ECW3_V7              NUMBER(8,3),
   ECW4_V7              NUMBER(8,3),
   TRP_V7               NUMBER(8,3),
   EPRC_V8              NUMBER(8,3),
   T2_V8                NUMBER(8,3),
   P2_V8                NUMBER(8,3),
   MN_V8                NUMBER(8,3),
   ECW3_V8              NUMBER(8,3),
   ECW4_V8              NUMBER(8,3),
   TRP_V8               NUMBER(8,3),
   EPRC_V9              NUMBER(8,3),
   T2_V9                NUMBER(8,3),
   P2_V9                NUMBER(8,3),
   MN_V9                NUMBER(8,3),
   ECW3_V9              NUMBER(8,3),
   ECW4_V9              NUMBER(8,3),
   TRP_V9               NUMBER(8,3),
   EPRC_X1              NUMBER(8,3),
   T2_X1                NUMBER(8,3),
   P2_X1                NUMBER(8,3),
   MN_X1                NUMBER(8,3),
   ECW3_X1              NUMBER(8,3),
   ECW4_X1              NUMBER(8,3),
   TRP_X1               NUMBER(8,3),
   UPDATE_DATE          DATE,
   EPRC_X2              NUMBER(8,3),
   T2_X2                NUMBER(8,3),
   P2_X2                NUMBER(8,3),
   MN_X2                NUMBER(8,3),
   ECW3_X2              NUMBER(8,3),
   ECW4_X2              NUMBER(8,3),
   TRP_X2               NUMBER(8,3),
   EPRC_X3              NUMBER(8,3),
   T2_X3                NUMBER(8,3),
   P2_X3                NUMBER(8,3),
   MN_X3                NUMBER(8,3),
   ECW3_X3              NUMBER(8,3),
   ECW4_X3              NUMBER(8,3),
   TRP_X3               NUMBER(8,3),
   EPRC_X4              NUMBER(8,3),
   T2_X4                NUMBER(8,3),
   P2_X4                NUMBER(8,3),
   MN_X4                NUMBER(8,3),
   ECW3_X4              NUMBER(8,3),
   ECW4_X4              NUMBER(8,3),
   TRP_X4               NUMBER(8,3),
   EPRC_X5              NUMBER(8,3),
   T2_X5                NUMBER(8,3),
   P2_X5                NUMBER(8,3),
   MN_X5                NUMBER(8,3),
   ECW3_X5              NUMBER(8,3),
   ECW4_X5              NUMBER(8,3),
   TRP_X5               NUMBER(8,3),
   EPRC_X6              NUMBER(8,3),
   T2_X6                NUMBER(8,3),
   P2_X6                NUMBER(8,3),
   MN_X6                NUMBER(8,3),
   ECW3_X6              NUMBER(8,3),
   ECW4_X6              NUMBER(8,3),
   TRP_X6               NUMBER(8,3),
   EPRC_X7              NUMBER(8,3),
   T2_X7                NUMBER(8,3),
   P2_X7                NUMBER(8,3),
   MN_X7                NUMBER(8,3),
   ECW3_X7              NUMBER(8,3),
   ECW4_X7              NUMBER(8,3),
   TRP_X7               NUMBER(8,3),
   EPRC_X8              NUMBER(8,3),
   T2_X8                NUMBER(8,3),
   P2_X8                NUMBER(8,3),
   MN_X8                NUMBER(8,3),
   ECW3_X8              NUMBER(8,3),
   ECW4_X8              NUMBER(8,3),
   TRP_X8               NUMBER(8,3),
   EPRC_X9              NUMBER(8,3),
   T2_X9                NUMBER(8,3),
   P2_X9                NUMBER(8,3),
   MN_X9                NUMBER(8,3),
   ECW3_X9              NUMBER(8,3),
   ECW4_X9              NUMBER(8,3),
   TRP_X9               NUMBER(8,3)
);

COMMENT ON COLUMN "A_DFD_A06IAEV25_LIST".ID IS
'系统编号';

COMMENT ON COLUMN "A_DFD_A06IAEV25_LIST".MSG_NO IS
'报文编号';

COMMENT ON COLUMN "A_DFD_A06IAEV25_LIST".ACNUM IS
'飞机号';

COMMENT ON COLUMN "A_DFD_A06IAEV25_LIST".RPTDATE IS
'报文时间
2012-1-1 00:00:00';

COMMENT ON COLUMN "A_DFD_A06IAEV25_LIST".CODE IS
'发送编码';

/*==============================================================*/
/* Index: "INDEX_197"                                           */
/*==============================================================*/
CREATE INDEX "INDEX_197" ON "A_DFD_A06IAEV25_LIST" (
   MSG_NO ASC
);

/*==============================================================*/
/* Index: "INDEX_198"                                           */
/*==============================================================*/
CREATE INDEX "INDEX_198" ON "A_DFD_A06IAEV25_LIST" (
   ACNUM ASC
);

/*==============================================================*/
/* Index: "INDEX_199"                                           */
/*==============================================================*/
CREATE INDEX "INDEX_199" ON "A_DFD_A06IAEV25_LIST" (
   RPTDATE ASC
);