CREATE OR REPLACE VIEW V_L_APU_SWAPLOG AS
SELECT L.ID, --APU拆换日志，时间转换为小时
       L.AIRCRAFTID,
       AC.BASEORGID,
       AC.ACMODELID,
       L.APUMODELID,
       L.APUID,
       L.APUID APU_ID,
       L.SWAP_DATE,
       L.SWAP_DATE_STR,
       L.SWAP_REASON,
       L.SWAP_ACTION,
       L.FAULT_DESC,
       ROUND(TIME_ONINSTALL/60,3) TIME_ONINSTALL,
       CYCLE_ONINSTALL,
       ROUND(TIME_ONREPAIRED/60,3) TIME_ONREPAIRED,
       CYCLE_ONREPAIRED,
       ROUND(TIME_ONREMOVE/60,3) TIME_ONREMOVE,
       L.CYCLE_ONREMOVE,
       L.REPAIR_FLAG,
       L.COMMENTS,
       L.UPDATE_MAN,
       L.UPDATE_TIME
  FROM L_APU_SWAPLOG L,B_AIRCRAFT AC
WHERE AC.ID= L.AIRCRAFTID;


