CREATE TABLE "A_DFD_A05IAEV25_LIST"  (
   ID                   NUMBER(18)                      NOT NULL,
   MSG_NO               NUMBER(18),
   ACNUM                VARCHAR2(16),
   RPTDATE              DATE,
   CODE                 VARCHAR2(16),
   ESN_EC               VARCHAR2(16),
   EHRS_EC              NUMBER(8,3),
   ECYC_EC              NUMBER(8,3),
   AP_EC                VARCHAR2(16),
   ESN_EE               VARCHAR2(16),
   EHRS_EE              NUMBER(8,3),
   ECYC_EE              NUMBER(8,3),
   AP_EE                VARCHAR2(16),
   ECW3_N1              VARCHAR2(16),
   ECW4_N1              VARCHAR2(16),
   EVM_N1               VARCHAR2(16),
   ECW3_N2              VARCHAR2(16),
   ECW4_N2              VARCHAR2(16),
   EVM_N2               VARCHAR2(16),
   EPR_S1               NUMBER(8,3),
   EGT_S1               NUMBER(8,3),
   N1_S1                NUMBER(8,3),
   N2_S1                NUMBER(8,3),
   FF_S1                NUMBER(8,3),
   VB1_S1               NUMBER(8,3),
   VB2_S1               NUMBER(8,3),
   EPR_S2               NUMBER(8,3),
   EGT_S2               NUMBER(8,3),
   N1_S2                NUMBER(8,3),
   N2_S2                NUMBER(8,3),
   FF_S2                NUMBER(8,3),
   VB1_S2               NUMBER(8,3),
   VB2_S2               NUMBER(8,3),
   EPR_S3               NUMBER(8,3),
   EGT_S3               NUMBER(8,3),
   N1_S3                NUMBER(8,3),
   N2_S3                NUMBER(8,3),
   FF_S3                NUMBER(8,3),
   VB1_S3               NUMBER(8,3),
   VB2_S3               NUMBER(8,3),
   EPR_S4               NUMBER(8,3),
   EGT_S4               NUMBER(8,3),
   N1_S4                NUMBER(8,3),
   N2_S4                NUMBER(8,3),
   FF_S4                NUMBER(8,3),
   VB1_S4               NUMBER(8,3),
   VB2_S4               NUMBER(8,3),
   EPR_S5               NUMBER(8,3),
   EGT_S5               NUMBER(8,3),
   N1_S5                NUMBER(8,3),
   N2_S5                NUMBER(8,3),
   FF_S5                NUMBER(8,3),
   VB1_S5               NUMBER(8,3),
   VB2_S5               NUMBER(8,3),
   EPR_S6               NUMBER(8,3),
   EGT_S6               NUMBER(8,3),
   N1_S6                NUMBER(8,3),
   N2_S6                NUMBER(8,3),
   FF_S6                NUMBER(8,3),
   VB1_S6               NUMBER(8,3),
   VB2_S6               NUMBER(8,3),
   EPR_S7               NUMBER(8,3),
   EGT_S7               NUMBER(8,3),
   N1_S7                NUMBER(8,3),
   N2_S7                NUMBER(8,3),
   FF_S7                NUMBER(8,3),
   VB1_S7               NUMBER(8,3),
   VB2_S7               NUMBER(8,3),
   EPR_S8               NUMBER(8,3),
   EGT_S8               NUMBER(8,3),
   N1_S8                NUMBER(8,3),
   N2_S8                NUMBER(8,3),
   FF_S8                NUMBER(8,3),
   VB1_S8               NUMBER(8,3),
   VB2_S8               NUMBER(8,3),
   EPR_S9               NUMBER(8,3),
   EGT_S9               NUMBER(8,3),
   N1_S9                NUMBER(8,3),
   N2_S9                NUMBER(8,3),
   FF_S9                NUMBER(8,3),
   VB1_S9               NUMBER(8,3),
   VB2_S9               NUMBER(8,3),
   EPR_S0               NUMBER(8,3),
   EGT_S0               NUMBER(8,3),
   N1_S0                NUMBER(8,3),
   N2_S0                NUMBER(8,3),
   FF_S0                NUMBER(8,3),
   VB1_S0               NUMBER(8,3),
   VB2_S0               NUMBER(8,3),
   EPR_T1               NUMBER(8,3),
   EGT_T1               NUMBER(8,3),
   N1_T1                NUMBER(8,3),
   N2_T1                NUMBER(8,3),
   FF_T1                NUMBER(8,3),
   VB1_T1               NUMBER(8,3),
   VB2_T1               NUMBER(8,3),
   EPR_T2               NUMBER(8,3),
   EGT_T2               NUMBER(8,3),
   N1_T2                NUMBER(8,3),
   N2_T2                NUMBER(8,3),
   FF_T2                NUMBER(8,3),
   VB1_T2               NUMBER(8,3),
   VB2_T2               NUMBER(8,3),
   EPR_T3               NUMBER(8,3),
   EGT_T3               NUMBER(8,3),
   N1_T3                NUMBER(8,3),
   N2_T3                NUMBER(8,3),
   FF_T3                NUMBER(8,3),
   VB1_T3               NUMBER(8,3),
   VB2_T3               NUMBER(8,3),
   EPR_T4               NUMBER(8,3),
   EGT_T4               NUMBER(8,3),
   N1_T4                NUMBER(8,3),
   N2_T4                NUMBER(8,3),
   FF_T4                NUMBER(8,3),
   VB1_T4               NUMBER(8,3),
   VB2_T4               NUMBER(8,3),
   EPR_T5               NUMBER(8,3),
   EGT_T5               NUMBER(8,3),
   N1_T5                NUMBER(8,3),
   N2_T5                NUMBER(8,3),
   FF_T5                NUMBER(8,3),
   VB1_T5               NUMBER(8,3),
   VB2_T5               NUMBER(8,3),
   EPR_T6               NUMBER(8,3),
   EGT_T6               NUMBER(8,3),
   N1_T6                NUMBER(8,3),
   N2_T6                NUMBER(8,3),
   FF_T6                NUMBER(8,3),
   VB1_T6               NUMBER(8,3),
   VB2_T6               NUMBER(8,3),
   EPR_T7               NUMBER(8,3),
   EGT_T7               NUMBER(8,3),
   N1_T7                NUMBER(8,3),
   N2_T7                NUMBER(8,3),
   FF_T7                NUMBER(8,3),
   VB1_T7               NUMBER(8,3),
   VB2_T7               NUMBER(8,3),
   EPR_T8               NUMBER(8,3),
   EGT_T8               NUMBER(8,3),
   N1_T8                NUMBER(8,3),
   N2_T8                NUMBER(8,3),
   FF_T8                NUMBER(8,3),
   VB1_T8               NUMBER(8,3),
   VB2_T8               NUMBER(8,3),
   EPR_T9               NUMBER(8,3),
   EGT_T9               NUMBER(8,3),
   N1_T9                NUMBER(8,3),
   N2_T9                NUMBER(8,3),
   FF_T9                NUMBER(8,3),
   VB1_T9               NUMBER(8,3),
   VB2_T9               NUMBER(8,3),
   EPR_T0               NUMBER(8,3),
   EGT_T0               NUMBER(8,3),
   N1_T0                NUMBER(8,3),
   N2_T0                NUMBER(8,3),
   FF_T0                NUMBER(8,3),
   EPR_V1               NUMBER(8,3),
   EGT_V1               NUMBER(8,3),
   N1_V1                NUMBER(8,3),
   N2_V1                NUMBER(8,3),
   FF_V1                NUMBER(8,3),
   VB1_V1               NUMBER(8,3),
   VB2_V1               NUMBER(8,3),
   EPR_X1               NUMBER(8,3),
   EGT_X1               NUMBER(8,3),
   N1_X1                NUMBER(8,3),
   N2_X1                NUMBER(8,3),
   FF_X1                NUMBER(8,3),
   VB1_X1               NUMBER(8,3),
   VB2_X1               NUMBER(8,3),
   VB1_T0               NUMBER(8,3),
   VB2_T0               NUMBER(8,3),
   TAT_C3               NUMBER(8,3),
   ALT_C3               NUMBER(8,3),
   MN_C3                NUMBER(8,3),
   BLEEDSTATUS_C3       VARCHAR2(63),
   APU_C3               VARCHAR2(16),
   UPDATE_DATE          DATE
);

COMMENT ON COLUMN "A_DFD_A05IAEV25_LIST".ID IS
'系统编号';

COMMENT ON COLUMN "A_DFD_A05IAEV25_LIST".MSG_NO IS
'报文编号';

COMMENT ON COLUMN "A_DFD_A05IAEV25_LIST".ACNUM IS
'飞机号';

COMMENT ON COLUMN "A_DFD_A05IAEV25_LIST".RPTDATE IS
'报文时间
2012-1-1 00:00:00';

COMMENT ON COLUMN "A_DFD_A05IAEV25_LIST".CODE IS
'发送编码';

/*==============================================================*/
/* Index: "INDEX_215"                                           */
/*==============================================================*/
CREATE INDEX "INDEX_215" ON "A_DFD_A05IAEV25_LIST" (
   MSG_NO ASC
);

/*==============================================================*/
/* Index: "INDEX_216"                                           */
/*==============================================================*/
CREATE INDEX "INDEX_216" ON "A_DFD_A05IAEV25_LIST" (
   ACNUM ASC
);

/*==============================================================*/
/* Index: "INDEX_217"                                           */
/*==============================================================*/
CREATE INDEX "INDEX_217" ON "A_DFD_A05IAEV25_LIST" (
   RPTDATE ASC
);
