CREATE OR REPLACE VIEW V_A_DFD_A23_OXYSTATE AS
SELECT B.BASEORGID, --最新的氧气瓶状态
       B.OX_CAPACITY,
       B.PRESSURE,
       B.FLOW,
       T.ID,
       T.MSG_NO,
       T.ACNUM,
       T.DATE_UTC,
       T.CKPTT_MID_S13,
       T.SAT_MID_S13,
       T.PRES_MID_S13,
       T.CKPTT_MID_S46,
       T.SAT_MID_S46,
       T.PRES_MID_S46,
       T.DATETIME_MID_S46,
       T.PRES_ST_C15_S13,
       T.PRES_ST_C15_S46,
       ROUND(DECODE((B.FLOW * B.PRESSURE),0,0,(B.OX_CAPACITY * T.PRES_ST_C15_S46) /(B.FLOW * B.PRESSURE)),3) REMAIN_OXY,
       T.PRES_ST_S46_K K,
       T.PRES_ST_S46_B B,
       T.PRES_ESTLIMIT_DATE EST_DAY,
       T.RECORDTIME
  FROM A_DFD_A23_COMPUTE T, B_AIRCRAFT B
 WHERE T.ACNUM = B.AIRCRAFTSN
   AND T.MSG_NO = (SELECT MAX(MSG_NO) FROM A_DFD_A23_COMPUTE T2 WHERE T2.ACNUM=B.AIRCRAFTSN)
 ORDER BY T.ACNUM;

 
 