CREATE OR REPLACE VIEW V_PUB_DATATASKHIS AS
SELECT T.ID, --数据任务执行记录查看
       T.ID DATATASKID,
       T.DATATASKTEMPLETID,
       T.NAME,
       T.STATUS STATUS,
       T.LASTMASSAGE,
       T.RATE,
       --T.EXECLOG,
       --to_char(T.BEGINTIME,'YYYY-MM-DD HH24:mi:SS') BEGINTIME,
       --to_char(T.ENDTIME,'YYYY-MM-DD HH24:mi:SS') ENDTIME,
       T.BEGINTIME,
       T.ENDTIME,
       --T.TASKCONTENT,
       T.PARAMVALUE,
       DT.APPMODULE,
       DT.TASKCATEGORY,
       DT.TYPE,
       DT.CRONEXPRESSION,
       DT.CODE
  FROM PUB_DATATASK T,PUB_DATATASK_TEMPLET DT
 WHERE DT.ID = T.DATATASKTEMPLETID;


CREATE OR REPLACE VIEW V_DFD_TELEGRAPH_HEAD_VIEW AS
SELECT T.ID,  --解析成功的DFD报文，rptno在元原模板中区分
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC
 WHERE H.MSG_NO = T.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM;
 
CREATE OR REPLACE VIEW V_TELEGRAPH_A01C_VIEW AS
SELECT T.ID,  --ENGINE REPORT
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       H.DMU,
       L.ESN_1,
       L.ESN_2,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A01CFM56_5B_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND L.MSG_NO=H.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM;
 

CREATE OR REPLACE VIEW V_TELEGRAPH_A01I_VIEW AS
SELECT T.ID,  --ENGINE REPORT
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       H.DMU,
       L.ESN_1,
       L.ESN_2,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A01IAEV25_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND L.MSG_NO=H.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM;

CREATE OR REPLACE VIEW V_TELEGRAPH_A11I_VIEW AS
SELECT T.ID,  --ENGINE REPORT
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       H.DMU,
       L.ESN_1,
       L.ESN_2,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A11IAVE25_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND L.MSG_NO=H.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM;

CREATE OR REPLACE VIEW V_TELEGRAPH_A02C_VIEW AS
SELECT T.ID,  --ENGINE REPORT
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       H.DMU,
       L.ESN_1,
       L.ESN_2,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A02CFM56_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND L.MSG_NO=H.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM;
 
CREATE OR REPLACE VIEW V_TELEGRAPH_A02I_VIEW AS
SELECT T.ID,  --ENGINE REPORT
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       H.DMU,
       L.ESN_1,
       L.ESN_2,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A02IAEV25_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND L.MSG_NO=H.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM;
 
CREATE OR REPLACE VIEW V_TELEGRAPH_A04C_VIEW AS
SELECT T.ID,  --ENGINE REPORT
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       H.DMU,
       L.ESN_1,
       L.ESN_2,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A04CFM56_5B_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND L.MSG_NO=H.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM;
 
CREATE OR REPLACE VIEW V_TELEGRAPH_A04I_VIEW AS
SELECT T.ID,  --ENGINE REPORT
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       H.DMU,
       L.ESN_1,
       L.ESN_2,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A04IAEV25_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND L.MSG_NO=H.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM;
 
CREATE OR REPLACE VIEW V_TELEGRAPH_A05I_VIEW AS
SELECT T.ID,  --ENGINE REPORT
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       H.DMU,
       L.ESN_EC ESN_1,
       L.ESN_EE ESN_2,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A05IAEV25_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND L.MSG_NO=H.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM;
 
CREATE OR REPLACE VIEW V_TELEGRAPH_A06C_VIEW AS
SELECT T.ID,  --ENGINE REPORT
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       H.DMU,
       L.ESN_1,
       L.ESN_2,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A06CFM56_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND L.MSG_NO=H.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM;
 
CREATE OR REPLACE VIEW V_TELEGRAPH_A06I_VIEW AS
SELECT T.ID,  --ENGINE REPORT
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       H.DMU,
       L.ESN_1,
       L.ESN_2,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A06IAEV25_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND L.MSG_NO=H.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM;
 
CREATE OR REPLACE VIEW V_TELEGRAPH_A07C_VIEW AS
SELECT T.ID,  --ENGINE REPORT
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       H.DMU,
       L.ESN_1,
       L.ESN_2,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A07CFM56_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND L.MSG_NO=H.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM;
 
CREATE OR REPLACE VIEW V_TELEGRAPH_A07I_VIEW AS
SELECT T.ID,  --ENGINE REPORT
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       H.DMU,
       L.ESN_1,
       L.ESN_2,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A07IAVE25_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND L.MSG_NO=H.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM;
 
CREATE OR REPLACE VIEW V_TELEGRAPH_A09I_VIEW AS
SELECT T.ID,  --ENGINE REPORT
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       H.DMU,
       L.ESN_1,
       L.ESN_2,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A09IAVE25_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND L.MSG_NO=H.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM;
 
CREATE OR REPLACE VIEW V_TELEGRAPH_A10C_VIEW AS
SELECT T.ID,  --ENGINE REPORT
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       H.DMU,
       L.ESN_1,
       L.ESN_2,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A10CFM56_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND L.MSG_NO=H.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM;
 
CREATE OR REPLACE VIEW V_TELEGRAPH_A10I_VIEW AS
SELECT T.ID,  --ENGINE REPORT
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       H.DMU,
       L.ESN_1,
       L.ESN_2,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A10IAVE25_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND L.MSG_NO=H.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM;
 

CREATE OR REPLACE VIEW V_ACARS_TELEGRAPH_DFD AS
SELECT T.ID,  --报文解析结果查看
       T.MSG_NO,
       T.TRANS_TIME,
       T.AC_ID ACNUM,
       T.RPTNO,
       T.MODELCODE,
       T.MODELSERIES,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T,B_AIRCRAFT AC
 WHERE AC.AIRCRAFTSN= T.AC_ID;


CREATE OR REPLACE VIEW V_ACARS_TELEGRAPH_CFD AS
SELECT T.ID,  --CFD报文解析结果查看
       T.MSG_NO,
       T.TRANS_TIME,
       T.AC_ID ACNUM,
       T.RPTNO,
       T.MODELCODE,
       T.MODELSERIES,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.FLT_ID,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_CFD T,B_AIRCRAFT AC
 WHERE AC.AIRCRAFTSN= T.AC_ID;







