-- 模板生成脚本[T_A_DFD_A14_LIST_DATA]
-- ================start===========================================================
-- 删除模板明细数据
delete pub_templet_1_item where pk_pub_templet_1 in (select pk_pub_templet_1 from pub_templet_1 where templetcode = 'T_A_DFD_A14_LIST_DATA');
-- 删除模板分组信息
delete from PUB_TEMPLET_1_ITEM_GROUP where templetid in (select pk_pub_templet_1 from pub_templet_1 where templetcode = 'T_A_DFD_A14_LIST_DATA');
-- 判断是否已经存在模板
DECLARE TEMPL_COUNT NUMBER(6);
BEGIN
  SELECT COUNT(*) INTO TEMPL_COUNT FROM pub_templet_1 where templetcode ='T_A_DFD_A14_LIST_DATA';
  IF TEMPL_COUNT > 0 THEN
    -- 更新老的模板，ID没有变化
    UPDATE PUB_TEMPLET_1 SET  templetcode='T_A_DFD_A14_LIST_DATA', templetname='T_A_DFD_A14_LIST_DATA', tablename='V_A_DFD_A14_LIST_DATA', datasourcename='datasource_apms', pkname='ID', pksequencename='S_A_DFD_A14_LIST_DATA', savedtablename='A_DFD_A14_LIST_DATA', cardcustpanel=null, listcustpanel=null, dataconstraint=null, parent_pub_template=null, comefrom='0', ordersetting=null WHERE templetcode = 'T_A_DFD_A14_LIST_DATA';
  ELSE
    -- 插入新模板，新生成ID
    Insert Into PUB_TEMPLET_1 (pk_pub_templet_1, templetcode, templetname, tablename, datasourcename, pkname, pksequencename, savedtablename, cardcustpanel, listcustpanel, dataconstraint, parent_pub_template, comefrom, ordersetting) values (s_pub_templet_1.nextval, 'T_A_DFD_A14_LIST_DATA', 'T_A_DFD_A14_LIST_DATA', 'V_A_DFD_A14_LIST_DATA', 'datasource_apms', 'ID', 'S_A_DFD_A14_LIST_DATA', 'A_DFD_A14_LIST_DATA', null, null, null, null, '0', null);
  END IF;
  -- 插入模板分组
 -- 插入模板明细
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'ID', '系统编号', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '1', '145', '150', 'N', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'MSG_NO', 'ACARS报文编号', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '20', '100', '150', 'N', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'ACNUM', '飞机号', '文本框', null, null, 'Y', '2', 'N', null, null, null, null, '4', '145', '150', 'N', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'ROW_NUM', '行标数', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '5', '145', '150', 'N', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'ROW_TITLE', '行头', '文本框', null, null, 'Y', '2', 'N', null, null, null, null, '6', '40', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'NA_PERCENT', 'APU转速', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '7', '75', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'EGTA', 'APU排气温度', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '8', '90', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'WF', '燃油流量', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '15', '75', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'OTA', 'OTA', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '9', '40', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'IGV', 'IGV', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '10', '40', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'WB', '引气流量', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '11', '70', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'LCIT', 'LCIT', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '12', '50', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'PT', '引气压力', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '13', '70', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'P2A', '进口压力', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '16', '70', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'LCOT', 'LCOT', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '17', '50', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'RPTNO', '报文编号', '文本框', null, null, 'Y', '3', 'N', null, null, null, null, '2', '60', '200', 'N', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'SCV', '伺服活门位置', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '18', '90', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'HOT', '高位滑油温度', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '19', '90', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'GLA', '发电机负载', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '14', '85', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_DFD_A14_LIST_DATA'), 'RECDATETIME', '更新时间', '时间', null, null, 'Y', '2', 'N', null, null, null, null, '3', '145', '150', 'N', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, null, null, null, null, null, null, null, null, null);
  commit;
END;
/
-- ================end export of [T_A_DFD_A14_LIST_DATA]=============================================================

