-- 模板生成脚本[T_A_ACARS_TELEGRAPH_A46]
-- ================start===========================================================
-- 删除模板明细数据
delete pub_templet_1_item where pk_pub_templet_1 in (select pk_pub_templet_1 from pub_templet_1 where templetcode = 'T_A_ACARS_TELEGRAPH_A46');
-- 删除模板分组信息
delete from PUB_TEMPLET_1_ITEM_GROUP where templetid in (select pk_pub_templet_1 from pub_templet_1 where templetcode = 'T_A_ACARS_TELEGRAPH_A46');
-- 判断是否已经存在模板
DECLARE TEMPL_COUNT NUMBER(6);
BEGIN
  SELECT COUNT(*) INTO TEMPL_COUNT FROM pub_templet_1 where templetcode ='T_A_ACARS_TELEGRAPH_A46';
  IF TEMPL_COUNT > 0 THEN
    -- 更新老的模板，ID没有变化
    UPDATE PUB_TEMPLET_1 SET  templetcode='T_A_ACARS_TELEGRAPH_A46', templetname='T_A_ACARS_TELEGRAPH_A46', tablename='V_TELEGRAPH_A46_VIEW', datasourcename='datasource_apms', pkname='S_A_ACARS_TELEGRAPH ', pksequencename=null, savedtablename='V_TELEGRAPH_A46_VIEW', cardcustpanel='APMS', listcustpanel=null, dataconstraint=null, parent_pub_template=null, comefrom='0', ordersetting='DATE_UTC DESC' WHERE templetcode = 'T_A_ACARS_TELEGRAPH_A46';
  ELSE
    -- 插入新模板，新生成ID
    Insert Into PUB_TEMPLET_1 (pk_pub_templet_1, templetcode, templetname, tablename, datasourcename, pkname, pksequencename, savedtablename, cardcustpanel, listcustpanel, dataconstraint, parent_pub_template, comefrom, ordersetting) values (s_pub_templet_1.nextval, 'T_A_ACARS_TELEGRAPH_A46', 'T_A_ACARS_TELEGRAPH_A46', 'V_TELEGRAPH_A46_VIEW', 'datasource_apms', 'S_A_ACARS_TELEGRAPH ', null, 'V_TELEGRAPH_A46_VIEW', 'APMS', null, null, null, '0', 'DATE_UTC DESC');
  END IF;
  -- 插入模板分组
 -- 插入模板明细
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_ACARS_TELEGRAPH_A46'), 'ID', 'ID', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '1', '145', '150', 'N', '1', 'N', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_ACARS_TELEGRAPH_A46'), 'BASEORGID', '所属基地', '下拉框', 'select id ID#,code 编码,name 基地  from b_organization where orglevel=1;ds=datasource_apms', null, 'Y', '1', 'N', null, null, null, null, '2', '120', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_ACARS_TELEGRAPH_A46'), 'ERRINT', '解码状态', '下拉框', 'select d.value,d.valueen,d.valuecn from b_dictionary d where d.classname=''ACARS_TELEGRAPH'' AND d.attributename=''ERRINT'' ORDER BY SEQNO', null, 'Y', '2', 'N', null, null, null, null, '12', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_ACARS_TELEGRAPH_A46'), 'ERRMESSAGE', '错误消息', '文本框', null, null, 'Y', '2', 'N', null, null, null, null, '13', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_ACARS_TELEGRAPH_A46'), 'RECORD_TIME', '记录时间', '时间', null, null, 'Y', '2', 'N', null, null, null, null, '15', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_ACARS_TELEGRAPH_A46'), 'MSG_NO', '消息编号', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '16', '100', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_ACARS_TELEGRAPH_A46'), 'RPTNO', '报文编号', '文本框', null, null, 'Y', '3', 'N', null, null, null, null, '3', '70', '200', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_ACARS_TELEGRAPH_A46'), 'ACNUM', '飞机号', '文本框', null, null, 'Y', '1', 'N', null, null, null, null, '4', '70', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_ACARS_TELEGRAPH_A46'), 'ACMODELID', '机型', '参照', null, 'SELECT ID ID#,T.MODELSERIES 机型系列,T.MODELCODE 机型 FROM B_AIRCRAFT_MODEL T WHERE 1=1', 'Y', '1', 'N', null, null, null, null, '5', '110', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_ACARS_TELEGRAPH_A46'), 'MODELSERIES', '机型系列', '文本框', null, null, 'Y', '2', 'N', null, null, null, null, '7', '100', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_ACARS_TELEGRAPH_A46'), 'DATE_UTC', '报文时间', '时间', null, null, 'Y', '1', 'N', null, null, null, null, '8', '150', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, '日期范围', null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_ACARS_TELEGRAPH_A46'), 'ESN_1', '左发序号', '文本框', null, null, 'Y', '1', 'N', null, null, null, null, '9', '110', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_ACARS_TELEGRAPH_A46'), 'ESN_2', '右发序号', '文本框', null, null, 'Y', '1', 'N', null, null, null, null, '10', '110', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_A_ACARS_TELEGRAPH_A46'), 'DMU', 'DMU版本', '文本框', null, null, 'Y', '1', 'N', null, null, null, null, '11', '110', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
  commit;
END;
/
-- ================end export of [T_A_ACARS_TELEGRAPH_A46]=============================================================

