CREATE OR REPLACE VIEW V_DFD_TELEGRAPH_HEAD_A13 AS
SELECT T.ID,  --解析成功的A13报文
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       L.ASN,L.AHRS,L.ACYC,L.AHRS_ADD,L.ACYC_ADD,
       L.CODE,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A13_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM AND L.MSG_NO=H.MSG_NO
   AND H.RPTNO = ANY('A13','R13' );

CREATE OR REPLACE VIEW V_DFD_TELEGRAPH_HEAD_A14 AS
SELECT T.ID,  --解析成功的A14报文
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       L.ASN,L.AHRS,L.ACYC,
       L.CODE,L.ECID,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A14_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM AND L.MSG_NO=H.MSG_NO
   AND H.RPTNO = ANY('A14','R14' );

CREATE OR REPLACE VIEW V_DFD_TELEGRAPH_HEAD_A38 AS
SELECT T.ID,  --解析成功的A38报文
       T.MSG_NO,
       H.DATE_UTC,
       H.RPTNO,
       H.ACNUM,
       L.ASN_E1 ASN,L.AHRS_E1 AHRS,L.ACYC_E1 ACYC,
       L.CODE,
       H.ACMODEL MODELCODE,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.MODELSERIES,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T, A_DFD_HEAD H,B_AIRCRAFT AC,A_DFD_A38_LIST L
 WHERE H.MSG_NO = T.MSG_NO AND AC.AIRCRAFTSN=H.ACNUM AND L.MSG_NO=H.MSG_NO;
 
 
CREATE OR REPLACE VIEW V_ACARS_TELEGRAPH_DFD AS
SELECT T.ID,  --报文解析结果查看
       T.MSG_NO,
       T.TRANS_TIME,
       T.AC_ID ACNUM,
       T.RPTNO,
       T.MODELCODE,
       T.MODELSERIES,
       AC.ACMODELID,
       AC.BASEORGID,
       AC.AIRLINEID,
       T.TEL_CONTENT,
       T.RECORD_TIME,
       T.PARSETIME,
       T.FDIMUVERSION,
       T.ERRINT,
       T.ERRMESSAGE
  FROM A_ACARS_TELEGRAPH_DFD T,B_AIRCRAFT AC
 WHERE AC.AIRCRAFTSN= T.AC_ID;


CREATE OR REPLACE VIEW V_DFD_UNSPPORTDMU AS
SELECT DISTINCT FDIMUVERSION,AC_ID,RPTNO  --不支持的软件版本号 
 FROM A_ACARS_TELEGRAPH_DFD T 
 WHERE T.ERRINT = 20 AND T.TRANS_TIME > (SYSDATE - 180);
 
CREATE OR REPLACE VIEW V_DFD_UNSPPORTMODEL AS
SELECT DISTINCT AC_ID,MODELCODE --不支持的机型
FROM A_ACARS_TELEGRAPH_DFD T 
WHERE T.ERRINT = 19 AND T.TRANS_TIME > (SYSDATE - 180);
 

CREATE OR REPLACE VIEW V_USER_BASEORG AS
SELECT ID,--用户、用户所有维修基地
       NAME, TELEPHONE,MOBILE,EMAIL,NO,LOGINNAME,ACCOUNTSTATUS,
       (SELECT O.ID FROM B_ORGANIZATION O  WHERE O.ORGLEVEL=1
          START WITH O.ID=U.ORGID_BASE CONNECT BY PRIOR O.PARENTORGID=O.ID ) BASEORGID,--所属维修基地
       ORGID_BASE ORGID
FROM B_USER U;


CREATE OR REPLACE VIEW V_MSGTEMPLATE_USER AS
SELECT --消息模板与订阅人视图
   U.ID,U.NAME,U.LOGINNAME,U.MOBILE,U.EMAIL,U.NO,
   (SELECT O.ID FROM B_ORGANIZATION O  WHERE O.ORGLEVEL=1
          START WITH O.ID=U.ORGID_BASE CONNECT BY PRIOR O.PARENTORGID=O.ID ) BASEORGID,U.ORGID_BASE ORGID,
   R.ISEMAIL,R.ISSMS,R.MSGTEMPLATEID,R.ID DISPATCHRULEID
FROM ALARM_MSGDISPATCHRULE R,B_USER U
WHERE R.SUBSCRIBERID=U.ID AND R.ISORGFILTER=0;

CREATE OR REPLACE VIEW V_A15A16LIST_VIEW AS
SELECT H.RPTNO,
       H.FLY_FROM,
       H.FLY_TO,
       H.FLT,
       H.PH,
       H.CNT,
       H.CODE,
       H.BLEED_STATUS,
       H.APU,
       H.TAT,
       H.ALT,
       H.CAS,
       H.MN,
       H.GW,
       H.CG,
       H.DMU,
       H.STATUS,
       T.ID,
       T.MSG_NO,
       T.ACNUM,
       T.DATE_UTC,
       T.ESN_1,
       T.EHRS_1,
       T.AP_1,
       T.FLAP_1,
       T.SLAT_1,
       T.ESN_2,
       T.EHRS_2,
       T.AP_2,
       T.FLAP_2,
       T.SLAT_2,
       T.MAX_E1,
       T.LIM_E1,
       T.RALT_S1,
       T.RALR_S1,
       T.PTCH_S1,
       T.PTCR_S1,
       T.ROLL_S1,
       T.ROLR_S1,
       T.YAW_S1,
       T.RALT_S2,
       T.RALR_S2,
       T.PTCH_S2,
       T.PTCR_S2,
       T.ROLL_S2,
       T.ROLR_S2,
       T.YAW_S2,
       T.VRTA_S3,
       T.LONA_S3,
       T.LATA_S3,
       T.RALR_S3,
       T.VRTA_S4,
       T.LONA_S4,
       T.LATA_S4,
       T.RALR_S4,
       T.RALT_T1,
       T.RALR_T1,
       T.PTCH_T1,
       T.PTCR_T1,
       T.ROLL_T1,
       T.ROLR_T1,
       T.YAW_T1,
       T.RALT_T2,
       T.RALR_T2,
       T.PTCH_T2,
       T.PTCR_T2,
       T.ROLL_T2,
       T.ROLR_T2,
       T.YAW_T2,
       T.VRTA_T3,
       T.LONA_T3,
       T.LATA_T3,
       T.VRTA_T4,
       T.LONA_T4,
       T.LATA_T4,
       T.COUNT,
       T.UPDATE_DATE
  FROM a_dfd_a15a16_list T, A_DFD_HEAD H
 WHERE H.MSG_NO = T.MSG_NO;
