COMMENT ON TABLE A_DFD_A13_LIST IS
'A13 APU启动报解码数据';

COMMENT ON COLUMN A_DFD_A13_LIST.ID IS
'系统编号';

COMMENT ON COLUMN A_DFD_A13_LIST.MSG_NO IS
'ACARS报文编号';

COMMENT ON COLUMN A_DFD_A13_LIST.ACNUM IS
'飞机号';

COMMENT ON COLUMN A_DFD_A13_LIST.DATE_UTC IS
'报文时间';

COMMENT ON COLUMN A_DFD_A13_LIST.CODE IS
'发送代码';

COMMENT ON COLUMN A_DFD_A13_LIST.TAT IS
'外界温度 X99.9 需要补小数点';

COMMENT ON COLUMN A_DFD_A13_LIST.ALT IS
'气压海拔XXXXX 数值 单位 英尺';

COMMENT ON COLUMN A_DFD_A13_LIST.ASN IS
'APU序号';

COMMENT ON COLUMN A_DFD_A13_LIST.AHRS IS
'APU小时 的单位 是小时,按分钟存储  解码数据*60';

COMMENT ON COLUMN A_DFD_A13_LIST.ACYC IS
'APU循环';

COMMENT ON COLUMN A_DFD_A13_LIST.AHRS_ADD IS
'APU小时 增量';

COMMENT ON COLUMN A_DFD_A13_LIST.ACYC_ADD IS
'APU循环 增量';

COMMENT ON COLUMN A_DFD_A13_LIST.ECID IS
'ECB识别ID A330 A340';

COMMENT ON COLUMN A_DFD_A13_LIST.PFAD IS
'APU性能参数';

COMMENT ON COLUMN A_DFD_A13_LIST.ACW1 IS
'APU控制字 A330 A340';

COMMENT ON COLUMN A_DFD_A13_LIST.ESN_N1 IS
'ENG1发动机序号';

COMMENT ON COLUMN A_DFD_A13_LIST.ACW1_N1 IS
'APU控制字1';

COMMENT ON COLUMN A_DFD_A13_LIST.ACW2_N1 IS
'APU控制字2';

COMMENT ON COLUMN A_DFD_A13_LIST.NA_N1 IS
'APU启动1发转速 需要标点 999.9';

COMMENT ON COLUMN A_DFD_A13_LIST.EGTA_N1 IS
'启动1发的排气温度 X999';

COMMENT ON COLUMN A_DFD_A13_LIST.IGV_N1 IS
'IGV角度 X99 单位 度';

COMMENT ON COLUMN A_DFD_A13_LIST.SCV_N1 IS
'伺服控制活门位置 A330 A340';

COMMENT ON COLUMN A_DFD_A13_LIST.HOT_N1 IS
'高位OIL温度 A330 A340';

COMMENT ON COLUMN A_DFD_A13_LIST.ESN_N2 IS
'ENG2发动机序号';

COMMENT ON COLUMN A_DFD_A13_LIST.ACW1_N2 IS
'APU控制字1';

COMMENT ON COLUMN A_DFD_A13_LIST.ACW2_N2 IS
'APU控制字2';

COMMENT ON COLUMN A_DFD_A13_LIST.NA_N2 IS
'APU启动1发转速 需要标点 999.9';

COMMENT ON COLUMN A_DFD_A13_LIST.EGTA_N2 IS
'启动2发的排气温度 X999';

COMMENT ON COLUMN A_DFD_A13_LIST.IGV_N2 IS
'IGV角度 X99 单位 度';

COMMENT ON COLUMN A_DFD_A13_LIST.SCV_N2 IS
'伺服控制活门位置 A330 A340';

COMMENT ON COLUMN A_DFD_A13_LIST.HOT_N2 IS
'高位OIL温度 A330 A340';

COMMENT ON COLUMN A_DFD_A13_LIST.ESN_N3 IS
'发动机启动完成';

COMMENT ON COLUMN A_DFD_A13_LIST.ACW1_N3 IS
'APU控制字1';

COMMENT ON COLUMN A_DFD_A13_LIST.ACW2_N3 IS
'APU控制字2';

COMMENT ON COLUMN A_DFD_A13_LIST.NA_N3 IS
'APU发动机启动完成转速 需要标点 999.9';

COMMENT ON COLUMN A_DFD_A13_LIST.EGTA_N3 IS
'发动机启动完成的排气温度 X999';

COMMENT ON COLUMN A_DFD_A13_LIST.IGV_N3 IS
'IGV角度 X99 单位 度';

COMMENT ON COLUMN A_DFD_A13_LIST.SCV_N3 IS
'伺服控制活门位置 A330 A340';

COMMENT ON COLUMN A_DFD_A13_LIST.HOT_N3 IS
'高位OIL温度 A330 A340';

COMMENT ON COLUMN A_DFD_A13_LIST.P2A_S1 IS
'启动1发压气机进口压力 9.999 单位 Bar';

COMMENT ON COLUMN A_DFD_A13_LIST.LCIT_S1 IS
'启动1发压气机进口温度 X999 温度 不需补小数点 单位 度';

COMMENT ON COLUMN A_DFD_A13_LIST.WB_S1 IS
'启动1发引气流量  需要标点  9.99  单位 kg/sec';

COMMENT ON COLUMN A_DFD_A13_LIST.PT_S1 IS
'启动1发引气压力';

COMMENT ON COLUMN A_DFD_A13_LIST.LCDT_S1 IS
'启动1发负载压气机出口温度XXXX度A330 A340LCOT ';

COMMENT ON COLUMN A_DFD_A13_LIST.OTA_S1 IS
'启动1发滑油温度XXX LOT_N1低位OIL温度 A330 A340';

COMMENT ON COLUMN A_DFD_A13_LIST.GLA_S1 IS
'启动1发发电机负载 XXX 单位 %';

COMMENT ON COLUMN A_DFD_A13_LIST.P2A_S2 IS
'启动2发压气机进口压力记小数点 9.999 单位 Bar';

COMMENT ON COLUMN A_DFD_A13_LIST.LCIT_S2 IS
'启动2发压气机进口温度 X999 温度 不需补小数点 单位 度';

COMMENT ON COLUMN A_DFD_A13_LIST.WB_S2 IS
'启动2发引气流量 999 需要标点  9.99  单位 kg/sec';

COMMENT ON COLUMN A_DFD_A13_LIST.PT_S2 IS
'启动2发引气压力';

COMMENT ON COLUMN A_DFD_A13_LIST.LCDT_S2 IS
'启动2发负载压气机出口温度XXXX度A330 A340LCOT ';

COMMENT ON COLUMN A_DFD_A13_LIST.OTA_S2 IS
'启动2发滑油温度XXX LOT_N2低位OIL温度 A330 A340';

COMMENT ON COLUMN A_DFD_A13_LIST.GLA_S2 IS
'启动2发发电机负载 XXX 单位 %';

COMMENT ON COLUMN A_DFD_A13_LIST.P2A_S3 IS
'启动完成压气机进口压力 9.999 单位 Bar';

COMMENT ON COLUMN A_DFD_A13_LIST.LCIT_S3 IS
'启动完成压气机进口温度 X999 温度 不需补小数点 单位 度';

COMMENT ON COLUMN A_DFD_A13_LIST.WB_S3 IS
'启动完成引气流量 999 需要标点  9.99  单位 kg/sec';

COMMENT ON COLUMN A_DFD_A13_LIST.PT_S3 IS
'启动完成引气压力';

COMMENT ON COLUMN A_DFD_A13_LIST.LCDT_S3 IS
'启动完成负载压气机出口温度 XXXX度 A330 A340LCOT ';

COMMENT ON COLUMN A_DFD_A13_LIST.OTA_S3 IS
'启动完成滑油温度 XXX LOT_N3低位OIL温度 A330 A340';

COMMENT ON COLUMN A_DFD_A13_LIST.GLA_S3 IS
'启动完成发电机负载 XXX 单位 %';

COMMENT ON COLUMN A_DFD_A13_LIST.STA_V1 IS
'APU自启动时间';

COMMENT ON COLUMN A_DFD_A13_LIST.EGTP_V1 IS
'APU自启动EGT峰值';

COMMENT ON COLUMN A_DFD_A13_LIST.NPA_V1 IS
'APU自启动EGT峰值的转速 XXX.X 单位%';

COMMENT ON COLUMN A_DFD_A13_LIST.OTA_V1 IS
'APU自启动滑油温度 LOT A330 A340';

COMMENT ON COLUMN A_DFD_A13_LIST.LCIT_V1 IS
'APU自启动进气口温度';

COMMENT ON COLUMN A_DFD_A13_LIST.CORRECT_FLAG IS
'修正标识0-未修正，1-修正';

COMMENT ON COLUMN A_DFD_A13_LIST.RECDATETIME IS
'更新时间';

COMMENT ON COLUMN A_DFD_A14_LIST.RPTDATE IS
'报文时间';

COMMENT ON COLUMN A_DFD_A14_LIST.CODE IS
'发送编码';

COMMENT ON COLUMN A_DFD_A14_LIST.ASN IS
'APU序号';

COMMENT ON COLUMN A_DFD_A14_LIST.AHRS IS
'APU小时 解码的单位 是小时 按分钟存储  解码数据*60';