CREATE OR REPLACE VIEW V_A33LIST_VIEW AS
SELECT
H.RPTNO,
H.ACMODEL,
H.FLY_FROM,
H.FLY_TO,
H.FLT,
H.PH,
H.CNT,
H.CODE,
H.BLEED_STATUS,
H.APU,
H.TAT,
H.ALT,
H.CAS,
H.MN,
H.GW,
H.CG,
H.DMU,
H.STATUS,
T.ID,T.MSG_NO,T.ACNUM,T.DATE_UTC,T.ESN_1,T.EHRS_1,T.ECYC_1,T.ESN_2,T.EHRS_2,T.ECYC_2,T.UPDATE_DATE
  FROM a_dfd_a33_list T, A_DFD_HEAD H
 WHERE H.MSG_NO = T.MSG_NO;
