CREATE OR REPLACE VIEW V_AIRCRAFT_A24_PDI_AC AS
SELECT --空调散热器性能
       AC.AIRCRAFTSN ACNUM,AC.BASEORGID, AC.ACMODELID,'PACK1#' POSITION,
       L.RPTDATE,L.TAT_V1,L.TW_S1,L.TP_S1,
        AM.MODELCODE,AM.MODELSERIES,
       L.RI_E1 RI,L.COT_E1 COT,L.PBV_E1 PBV,L.PF_E1 PF
 FROM B_AIRCRAFT AC,B_AIRCRAFT_MODEL AM,A_DFD_A24_LIST L
WHERE L.ACNUM =AC.AIRCRAFTSN AND AM.ID=AC.ACMODELID
 AND L.MSG_NO=(SELECT MAX(MSG_NO) FROM A_DFD_A24_LIST LT WHERE LT.ACNUM = AC.AIRCRAFTSN)
 UNION ALL
SELECT --空调散热器性能
       AC.AIRCRAFTSN ACNUM,AC.BASEORGID, AC.ACMODELID,'PACK2#' POSITION,
       L.RPTDATE,L.TAT_V1,L.TW_T1,L.TP_T1,
       AM.MODELCODE,AM.MODELSERIES,
       L.RI_N1 RI,L.COT_N1 COT,L.PBV_N1 PBV,L.PF_N1 PF
 FROM B_AIRCRAFT AC,B_AIRCRAFT_MODEL AM,A_DFD_A24_LIST L
WHERE L.ACNUM =AC.AIRCRAFTSN AND AM.ID=AC.ACMODELID
 AND L.MSG_NO=(SELECT MAX(MSG_NO) FROM A_DFD_A24_LIST LT WHERE LT.ACNUM = AC.AIRCRAFTSN);
