
--添加唯一约束
CREATE UNIQUE INDEX IDX_AP_POS_APTIDCODE_UNIQUE ON B_AIRPORT_POSITION (
   AIRPORTID ASC,
   CODE ASC
);

CREATE OR REPLACE VIEW V_FLIGHT_IMPORTANTCHANGE AS
SELECT --重要的航班变动信息
       C.ID,
       C.FLIGHTID,
       C.FLIGHTNO,
       S.ACNUM,
       S.ACMODEL,
       S.DEP_APT,
       S.ARR_APT,
       (select d.valuecn from b_dictionary d where d.classname='FLIGHTSCHEDULE'
               AND d.attributename='CHANGETYPE' and d.value=c.changetype) changetype_name,
       C.CHANGETYPE,
       C.CHANGETIME,

       S.CTD,
       S.CTA,
       C.BOARDCASTTIME,
        TO_CHAR(C.BOARDCASTTIME,'YYYY-MM-DD HH24:MI:SS') BOARDCASTTIME_STR,
       C.FLIGHTDATE,
       TO_CHAR(C.FLIGHTDATE,'MM-DD') FLIGHTDATE_SHORT,
       TO_CHAR(C.CHANGETIME,'MM-DD HH24:MI') CHANGETIME_STR,
       C.NEEDBOARDCAST,
       C.ISBOARDCAST,
       DECODE(C.NEEDBOARDCAST,0,'否',1,'是') NEEDBOARDCAST_NAME,
       DECODE(C.ISBOARDCAST,0,'否',1,'是') ISBOARDCAST_NAME,
       C.CHANGECONTENT,
       C.COMMENTS,
       C.RECIPIENT,
       S.MEMO,S.CANCEL_FLAG,S.CANCEL_TYPE,S.CANCEL_TIME,S.CANCEL_REASON,S.CANCEL_SRC,--取消相关
       (SELECT SHORTNAME FROM B_AIRPORT WHERE CODE_3=DEP_APT) DEP_APT_NAME,
       (SELECT SHORTNAME FROM B_AIRPORT WHERE CODE_3=ARR_APT) ARR_APT_NAME,
       C.UPDATETIME,
       C.UPDATEUSER
  FROM F_FLIGHT_CHANGELOG C,F_FLIGHT_SCHEDULE S
  WHERE S.FLT_PK=C.FLIGHTID
   AND C.CHANGETYPE = ANY(200,210,220,230,30,35) --取消、备降、返航、机场变更等
   AND C.ISBOARDCAST = 0 AND C.CHANGETIME> SYSDATE-2
   AND S.CTD < SYSDATE+1;
