CREATE OR REPLACE VIEW V_A27LIST_VIEW AS
SELECT
H.RPTNO,
H.ACMODEL,
H.FLY_FROM,
H.FLY_TO,
H.FLT,
H.PH,
H.CNT,
H.CODE,
H.BLEED_STATUS,
H.APU,
H.TAT,
H.ALT,
H.CAS,
H.MN,
H.GW,
H.CG,
H.Date_Utc,
H.DMU,
T.ID,T.MSG_NO,T.ACNUM,T.TMR27_PP,T.CKTMR_PP,T.ENDTMR_PP,T.DETQ_PP,T.ENDTQ_PP,T.OIQEXT_PP,T.OIQ_ENG1_Z4,T.OIQ_ENG2_Z4,T.ENG_SHUTTIME_Z4,T.OIQ_ENG1_Z5,T.OIQ_ENG2_Z5,T.ENG_SHUTTIME_Z5,T.OILADD_ENG1,T.ADDTIME_ENG1,T.PFAD_ENG1,T.PRE20S_ENG1,T.OIQST_ENG1,T.OIQOLD_ENG1,T.OILADD_ENG2,T.ADDTIME_ENG2,T.PFAD_ENG2,T.PRE20S_ENG2,T.OIQST_ENG2,T.OIQOLD_ENG2,T.QDT0_ENG1,T.QDT0_TIME_ENG1,T.QDT1_ENG1,T.QDT1_TIME_ENG1,T.QDT2_ENG1,T.QDT2_TIME_ENG1,T.QDT3_ENG1,T.QDT3_TIME_ENG1,T.QDT4_ENG1,T.QDT4_TIME_ENG1,T.QDT0_ENG2,T.QDT0_TIME_ENG2,T.QDT1_ENG2,T.QDT1_TIME_ENG2,T.QDT2_ENG2,T.QDT2_TIME_ENG2,T.QDT3_ENG2,T.QDT3_TIME_ENG2,T.QDT4_ENG2,T.QDT4_TIME_ENG2,T.CAL_GA_ENG1,T.CAL_AIR_ENG1,T.OIQAV_ENG1,T.OIQDT_ENG1,T.OIQCNT_ENG1,T.CAL_GA_ENG2,T.CAL_AIR_ENG2,T.OIQAV_ENG2,T.OIQDT_ENG2,T.OIQCNT_ENG2,T.QT_ENG1,T.FH_ENG1,T.OILCAL_ENG1,T.EMPLOYID,T.QT_ENG2,T.FH_ENG2,T.OILCAL_ENG2,T.UPDATE_DATE
 FROM a_dfd_a27_list T, A_DFD_HEAD H
 WHERE H.MSG_NO = T.MSG_NO;
