CREATE OR REPLACE VIEW V_MSGTEMPLATE_USERORG AS
SELECT --消息、人员视图,有所属基地限制
       U.ID,U.NAME,U.LOGINNAME,U.MOBILE,U.EMAIL,U.NO,U.BASEORGID,U.ORGID,
       R.ISEMAIL,R.ISSMS,R.MSGTEMPLATEID,AC.AIRCRAFTSN ACNUM,
       R.ID DISPATCHRULEID
FROM ALARM_MSGDISPATCHRULE R,B_AIRCRAFT AC,V_USER_BASEORG U
WHERE AC.BASEORGID=U.BASEORGID AND R.SUBSCRIBERID=U.ID AND R.ISORGFILTER=1;