--添加非空约束

--不正常快报表字段
ALTER TABLE F_UNUSUALFLT_REPORT MODIFY (NAME NOT NULL);
ALTER TABLE F_UNUSUALFLT_REPORT MODIFY (CODE NOT NULL);
ALTER TABLE F_UNUSUALFLT_REPORT MODIFY (FLIGHTID NOT NULL);
ALTER TABLE F_UNUSUALFLT_REPORT MODIFY (FLT_NO NOT NULL);
ALTER TABLE F_UNUSUALFLT_REPORT MODIFY (ACNUM NOT NULL);
ALTER TABLE F_UNUSUALFLT_REPORT MODIFY (AIRPORTID NOT NULL);
ALTER TABLE F_UNUSUALFLT_REPORT MODIFY (TYPE NOT NULL);
ALTER TABLE F_UNUSUALFLT_REPORT MODIFY (ISMAINTENANCEREASON NOT NULL);


--添加索引
CREATE UNIQUE INDEX IDX_UNUSUALFLT_CODE ON F_UNUSUALFLT_REPORT (
   CODE ASC
);
